# Site settings
author: Nicole Lucien
title: 
header-img: img/home-bg.png
email: nicolemlucien@gmail.com
copyright_name: Nicole Lucien
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: HerNameisNic
github_username:  nicmlu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
